"use client";
import { useEffect, useState } from "react";
import ModalConfirmacao from "@/components/ModalConfirmacao";
import SelectPadrao from "@/components/SelectPadrao";
interface Usuario { id:string; nome:string; email:string; papel:string; ativo:boolean; trocarSenha:boolean; ultimoAcesso:string|null; convidadoEm:string|null; }
const RP:Record<string,string>={ADMIN:"Administrador",OPERADOR:"Operador",LEITURA:"Leitura"};
export default function GerenciarUsuarios({meuId}:{meuId:string}){
 const [usuarios,setUsuarios]=useState<Usuario[]>([]),[carregando,setCarregando]=useState(true),[ocupado,setOcupado]=useState<string|null>(null),[erro,setErro]=useState<string|null>(null);
 const [nome,setNome]=useState(""),[email,setEmail]=useState(""),[papel,setPapel]=useState("OPERADOR"),[resultado,setResultado]=useState<string|null>(null),[salvandoUsuario,setSalvandoUsuario]=useState(false);
 const [novoAberto,setNovoAberto]=useState(false);
 const [editando,setEditando]=useState<Usuario|null>(null),[confirmar,setConfirmar]=useState<{u:Usuario;acao:"inativar"|"senha"|"excluir"}|null>(null);
 async function carregar(){setCarregando(true);const r=await fetch("/api/usuarios");if(r.ok)setUsuarios((await r.json()).usuarios);setCarregando(false)} useEffect(()=>{carregar()},[]);
 async function requisicao(u:Usuario,method:string,body?:object){setErro(null);setOcupado(u.id);try{const r=await fetch(`/api/usuarios/${u.id}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){setErro(d.erro??"Não foi possível concluir.");return false}await carregar();return true}finally{setOcupado(null)}}
 async function cadastrar(e:React.FormEvent){e.preventDefault();if(salvandoUsuario)return;setErro(null);setResultado(null);setSalvandoUsuario(true);try{const r=await fetch("/api/usuarios",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome,email,papel})});const d=await r.json();if(!r.ok){setErro(d.erro??"Não foi possível cadastrar.");return}setNome("");setEmail("");setPapel("OPERADOR");setNovoAberto(false);setResultado(d.emailEnviado?"Usuário cadastrado e convite enviado.":`Usuário cadastrado. Senha provisória: ${d.senhaProvisoria??"consulte o administrador"}`);if(d.usuario){setUsuarios(prev=>[d.usuario,...prev.filter(u=>u.id!==d.usuario.id)])}await carregar()}finally{setSalvandoUsuario(false)}}
 async function novaSenha(u:Usuario){setOcupado(u.id);const r=await fetch(`/api/usuarios/${u.id}/senha`,{method:"POST"});const d=await r.json();setOcupado(null);if(!r.ok){setErro(d.erro??"Não foi possível redefinir.");return}setResultado(d.emailEnviado?"Nova senha provisória enviada.":`Nova senha provisória: ${d.senhaProvisoria}`);await carregar()}
 const data=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";
 return <>
  <div className="fm-cadastro-toolbar fm-usuarios-toolbar"><div className="fm-cadastro-contagem"><span>{carregando?"Carregando...":`${usuarios.length} usuário${usuarios.length===1?"":"s"}`}</span><small>Acessos cadastrados no sistema</small></div><button type="button" className="botao fm-botao-novo" onClick={()=>setNovoAberto(true)}>+ Novo Usuário</button></div>
  {resultado&&<div className="aviso bom">{resultado}</div>}
  {erro&&<div className="erro">{erro}</div>}
  <div className="cartao tabela-rolagem fm-tabela-operacional fm-usuarios-tabela"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Situação</th><th>Último acesso</th><th style={{textAlign:"center"}}>Ações</th></tr></thead><tbody>{usuarios.map(u=><tr key={u.id}><td><strong>{u.nome}</strong></td><td>{u.email}</td><td><span className="perfil-pill">{RP[u.papel]??u.papel}</span></td><td><span className={`selo ${!u.ativo?"off":u.trocarSenha?"espera":"ok"}`}>{!u.ativo?"Inativo":u.trocarSenha?"Aguardando 1º acesso":"Ativo"}</span></td><td>{data(u.ultimoAcesso)}</td><td>{u.id===meuId?<span className="voce-pill">você</span>:<div className="acoes-linha"><button className="botao discreto mini" onClick={()=>setEditando({...u})}>Editar</button><button className="botao discreto mini" onClick={()=>setConfirmar({u,acao:"senha"})}>Nova senha</button><button className="botao discreto mini" onClick={()=>u.ativo?setConfirmar({u,acao:"inativar"}):requisicao(u,"PATCH",{ativo:true})}>{u.ativo?"Inativar":"Reativar"}</button><button className="botao perigo mini" onClick={()=>setConfirmar({u,acao:"excluir"})}>Excluir</button></div>}</td></tr>)}</tbody></table></div>
  {novoAberto&&<div className="fm-custo-modal-overlay" role="dialog" aria-modal="true" aria-label="Novo usuário" onMouseDown={()=>setNovoAberto(false)}><div className="fm-custo-modal fm-cadastro-modal" onMouseDown={e=>e.stopPropagation()}><div className="fm-custo-modal-cabecalho"><h2>Novo · Usuário</h2><button type="button" className="fm-custo-modal-fechar" aria-label="Fechar" onClick={()=>setNovoAberto(false)}>×</button></div><form onSubmit={cadastrar}><div className="fm-custo-modal-corpo"><section className="fm-custo-secao"><div className="fm-custo-secao-titulo">Identificação e acesso</div><div className="fm-custo-grid"><div className="fm-custo-campo"><label>Nome completo <b>*</b></label><input value={nome} onChange={e=>setNome(e.target.value)} required/></div><div className="fm-custo-campo"><label>E-mail <b>*</b></label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="fm-custo-campo"><label>Perfil <b>*</b></label><SelectPadrao value={papel} onChange={setPapel} options={[{value:"OPERADOR",label:"Operador"},{value:"LEITURA",label:"Leitura"},{value:"ADMIN",label:"Administrador"}]} ariaLabel="Perfil do usuário" /></div></div></section></div><div className="fm-custo-modal-rodape"><button type="button" className="botao discreto" onClick={()=>setNovoAberto(false)} disabled={salvandoUsuario}>Cancelar</button><button className="botao" type="submit" disabled={salvandoUsuario}>{salvandoUsuario?"Salvando…":"Cadastrar usuário"}</button></div></form></div></div>}
  {editando&&<div className="fm-custo-modal-overlay" role="dialog" aria-modal="true" aria-label="Editar usuário" onMouseDown={()=>setEditando(null)}><div className="fm-custo-modal fm-cadastro-modal" onMouseDown={e=>e.stopPropagation()}><div className="fm-custo-modal-cabecalho"><h2>Editar · Usuário</h2><button type="button" className="fm-custo-modal-fechar" aria-label="Fechar" onClick={()=>setEditando(null)}>×</button></div><form onSubmit={async e=>{e.preventDefault();if(await requisicao(editando,"PATCH",{nome:editando.nome,email:editando.email,papel:editando.papel}))setEditando(null)}}><div className="fm-custo-modal-corpo"><section className="fm-custo-secao"><div className="fm-custo-secao-titulo">Identificação e acesso</div><div className="fm-custo-grid"><div className="fm-custo-campo"><label>Nome completo <b>*</b></label><input value={editando.nome} onChange={e=>setEditando({...editando,nome:e.target.value})} required disabled={ocupado===editando.id}/></div><div className="fm-custo-campo"><label>E-mail <b>*</b></label><input type="email" value={editando.email} onChange={e=>setEditando({...editando,email:e.target.value})} required disabled={ocupado===editando.id}/></div><div className="fm-custo-campo"><label>Perfil <b>*</b></label><SelectPadrao value={editando.papel} onChange={(valor)=>setEditando({...editando,papel:valor})} options={[{value:"OPERADOR",label:"Operador"},{value:"LEITURA",label:"Leitura"},{value:"ADMIN",label:"Administrador"}]} ariaLabel="Perfil do usuário" /></div></div></section></div><div className="fm-custo-modal-rodape"><button type="button" className="botao discreto" onClick={()=>setEditando(null)} disabled={ocupado===editando.id}>Cancelar</button><button className="botao" type="submit" disabled={ocupado===editando.id}>{ocupado===editando.id?"Salvando…":"Salvar alterações"}</button></div></form></div></div>}
  {confirmar&&<ModalConfirmacao titulo={confirmar.acao==="excluir"?"Excluir usuário":confirmar.acao==="senha"?"Redefinir senha":"Inativar acesso"} confirmar={confirmar.acao==="excluir"?"Excluir definitivamente":confirmar.acao==="senha"?"Gerar nova senha":"Inativar"} perigo={confirmar.acao!=="senha"} ocupado={ocupado===confirmar.u.id} aoCancelar={()=>setConfirmar(null)} aoConfirmar={()=>{const x=confirmar;setConfirmar(null);if(x.acao==="senha")novaSenha(x.u);else if(x.acao==="excluir")requisicao(x.u,"DELETE");else requisicao(x.u,"PATCH",{ativo:false})}}><p>{confirmar.acao==="excluir"?<>A conta de <strong>{confirmar.u.nome}</strong> será removida do banco do aplicativo. O registro histórico de acesso será preservado.</>:confirmar.acao==="senha"?<>Será criada uma nova senha provisória para <strong>{confirmar.u.nome}</strong>.</>:<><strong>{confirmar.u.nome}</strong> perderá o acesso imediatamente.</>}</p></ModalConfirmacao>}
 </>
}





